### ISSUE TITLE
ページ遷移

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#12]
以下の画面遷移機能を実装すること
ヘッダーの商品検索をクリック→商品検索ページ(Products#index)
商品検索ページの各商品の右側の「商品詳細」ボタン→商品詳細ページ(Products#show)
ユーザー詳細ページの「修正/退会」ボタン→ユーザー修正ページ(Users#edit)

参考：https://pikawaka.com/rails/link_to#アプリ内でコードを書いてみよう

**Comment by imai0602** [comment]
# ToDo
- [ ] ヘッダーの修正（_header.html.erb ）
・link_toを使って、商品詳細画面のリンクとユーザー情報画面のリンクを作成

- [ ] ユーザー詳細ページ（users/show.html.erb）

・link_toを使って、修正・退会を押した時、ユーザー修正ページに飛ばす。

- [ ] 商品検索ページ(products/show.html.erb)

・link_toを使って、商品詳細ボタンを押した時、商品詳細ページに飛ばす。

予想工数　２h

**Comment by yuki-tachi0219** [comment]
問題なさそうなので、そのまま進めていただければと思います 🐧
